// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7diWJewXlTygDuA18YTWClcextwUJlvs',
    appId: '1:167400289197:web:2f8588451f4a449e0f2724',
    messagingSenderId: '167400289197',
    projectId: 'stay-indekos',
    authDomain: 'stay-indekos.firebaseapp.com',
    storageBucket: 'stay-indekos.appspot.com',
    measurementId: 'G-ZTZN1D9F08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEwYol28BhJG9_0cDghHIPh5muzK6eR1E',
    appId: '1:167400289197:android:4c6ea51472cce8cb0f2724',
    messagingSenderId: '167400289197',
    projectId: 'stay-indekos',
    storageBucket: 'stay-indekos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDckHaBKSm17uqvcdnXQlujC-nOQtshNsA',
    appId: '1:167400289197:ios:8061437456aa28610f2724',
    messagingSenderId: '167400289197',
    projectId: 'stay-indekos',
    storageBucket: 'stay-indekos.appspot.com',
    iosClientId: '167400289197-5prtnbagne6mi8vu7kvp0va9lthi3h6t.apps.googleusercontent.com',
    iosBundleId: 'com.example.stayIndekos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDckHaBKSm17uqvcdnXQlujC-nOQtshNsA',
    appId: '1:167400289197:ios:8061437456aa28610f2724',
    messagingSenderId: '167400289197',
    projectId: 'stay-indekos',
    storageBucket: 'stay-indekos.appspot.com',
    iosClientId: '167400289197-5prtnbagne6mi8vu7kvp0va9lthi3h6t.apps.googleusercontent.com',
    iosBundleId: 'com.example.stayIndekos',
  );
}
